### ISSUE TITLE
Usage qestion

### ISSUE THREAD

**Issue by eriksdev1** [peaceroad/p7d-markdown-it-p-captions#1]
Good day, is there chance you can explain how to make the plug in work in VS Code please, I installed it, I reloaded the window but I see no change after adding the words "fig" and a number with a dot:

`fig 1. Test Caption`

How can I auto number this ? 

Thanks !

**Comment by peaceroad** [comment]
Although the code is not well written, I think this markdown-it plugin will work.

The following vscode extension allows you to use this markdown-it plugin with vscode.
https://marketplace.visualstudio.com/items?itemName=peaceroad.p7d-markdown-it-p-captions

[Uploading ● test.md - Visual Studio Code 2024-02-20 17-18-51.mp4…
](https://github.com/peaceroad/p7d-markdown-it-p-captions/assets/1066782/d7d0e89b-ecfa-465c-b2fd-dcc7cc3cd6a6)

This plugin cannot automatically assign figure numbers (on vscode).
On my local computer, I have prepared a script that forces figure numbers from the terminal, but it currently does not support English.

Also, this markdown-it plugin does not wrap figures and captions in figure elements, so I usually use the following vscode extension that makes it possible.
https://marketplace.visualstudio.com/items?itemName=peaceroad.p7d-markdown-it-figure-with-p-caption
(However, this may not work if the vscode extension above does not work.)

thank you.
